export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'
export const INVALIDATE_PROFILE = 'INVALIDATE_PROFILE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_CHATROOM_REQUEST = 'FETCH_CHATROOM_REQUEST'
export const FETCH_CHATROOM_SUCCESS = 'FETCH_CHATROOM_SUCCESS'
export const FETCH_CHATROOM_FAILURE = 'FETCH_CHATROOM_FAILURE'

export const FETCH_CHATROOMS_REQUEST = 'FETCH_CHATROOMS_REQUEST'
export const FETCH_CHATROOMS_SUCCESS = 'FETCH_CHATROOMS_SUCCESS'
export const FETCH_CHATROOMS_FAILURE = 'FETCH_CHATROOMS_FAILURE'
