export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOGOUT = 'LOGOUT'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const INVALIDATE_USER = 'INVALIDATE_USER'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const ADD_USERS = 'ADD_USERS'

export const FETCH_CHATROOM_REQUEST = 'FETCH_CHATROOM_REQUEST'
export const FETCH_CHATROOM_SUCCESS = 'FETCH_CHATROOM_SUCCESS'
export const FETCH_CHATROOM_FAILURE = 'FETCH_CHATROOM_FAILURE'
export const ADD_CHATROOM_SUCCESS = 'ADD_CHATROOM_SUCCESS'
export const ADD_CHATROOM_FAILURE = 'ADD_CHATROOM_FAILURE'

export const FETCH_CHATROOMS_REQUEST = 'FETCH_CHATROOMS_REQUEST'
export const FETCH_CHATROOMS_SUCCESS = 'FETCH_CHATROOMS_SUCCESS'
export const FETCH_CHATROOMS_FAILURE = 'FETCH_CHATROOMS_FAILURE'

export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES'
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE'

export const ADD_GUEST_TO_CHATROOM_SUCCESS = 'ADD_GUEST_TO_CHATROOM_SUCCESS'
export const ADD_GUEST_TO_CHATROOM_FAILURE = 'ADD_GUEST_TO_CHATROOM_FAILURE'

export const SUBSCRIBE_TO_CHATROOM_MESSAGES = 'SUBSCRIBE_TO_CHATROOM_MESSAGES'
export const UNSUBSCRIBE_FROM_CHATROOM_MESSAGES = 'UNSUBSCRIBE_FROM_CHATROOM_MESSAGES'
export const SUBSCRIBE_TO_CHATROOM_SUGGESTIONS = 'SUBSCRIBE_TO_CHATROOM_SUGGESTIONS'
export const UNSUBSCRIBE_FROM_CHATROOM_SUGGESTIONS = 'UNSUBSCRIBE_FROM_CHATROOM_SUGGESTIONS'

export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS'
export const ADD_SUGGESTION_SUCCESS = 'ADD_SUGGESTION_SUCCESS'
export const REMOVE_SUGGESTION_SUCCESS = 'REMOVE_SUGGESTION_SUCCESS'
